### PR TITLE
Add map click in dropdown and remove map title

### PR DESCRIPTION
**Pull request by andyzhangstat**
Solve major issue and minor issue from Joel M4 feedback!

Add new function which we click the states, the name will show up on dropdown. 
And remove the title.

#85

### CODE REVIEW

**Review by Owl64901 — CHANGES_REQUESTED** [review]
It seems the basic selection does not work (either from dropdown or click).

**Comment by andyzhangstat** [comment]
> It seems the basic selection does not work (either from dropdown or click).

The dashboard is designed for new functionality. It's pointless to choose states in dropdown if we have all the states in a map.

**Review by Owl64901 — CHANGES_REQUESTED** [review]
I think Joel wanted our design to be able to select states via both a drop-down menu and by clicking on the state directly. 

Taking a step back, the current design does not have the selection function when clicking on a state, and the map will not change.

**Review by Prabh95 — CHANGES_REQUESTED** [review]
Hi @andyzhangstat, please fix these issues:
1) Once I select the state on the map, the state code filter gets updated but the map is not updated with that selected state.

2) Secondly the dropdown is not working now. As per Joel, the map select is an added feature but **all the filters should work as expected.**

**Review by Owl64901 — APPROVED** [review]
Looks good!

**Review by Owl64901 — APPROVED** [review]
Looks good!

**Pull request merged**
